apiVersion: v1
kind: Service
metadata:
  name: ssh-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ssh-backend
  ports:
  - name: ssh
    port: 22         # LB external port
    targetPort: 2222 # Container’s internal SSH port
