apiVersion: v1
kind: ConfigMap
metadata:
  name: ssh-auth-keys
  namespace: default
data:
  authorized_keys: |
    <ssh-key>
    # You can put multiple keys, each on its own line
    # then to ssh: ssh -i <path to ssh public key> sshuser@<lb-external-ip>
    # e.g. ssh -i ~/.ssh/id_ed25519 sshuser@91.106.223.215
    # may have to run ssh-keygen -R <lb-external-ip> in case you get "WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!"
