---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crusoe-lb-controller.serviceAccountName" . }}
  namespace: {{ .Values.controller.namespace }}
  labels:
    {{- include "crusoe-lb-controller.selectorLabels" . | nindent 6 }}

---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "crusoe-lb-controller.fullname" . }}
  labels:
    {{- include "crusoe-lb-controller.selectorLabels" . | nindent 8 }}
rules:
  - apiGroups: [""]
    resources:
      - services
    verbs: ["get", "create", "list", "watch", "update", "patch"]
  - apiGroups: [""] 
    resources:
      - nodes
    verbs: ["list", "get", "watch"]
  - apiGroups: [""] 
    resources:
      - services/status
    verbs: ["patch", "update", "get"]

---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "crusoe-lb-controller.fullname" . }}
  labels:
    {{- include "crusoe-lb-controller.selectorLabels" . | nindent 6 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "crusoe-lb-controller.serviceAccountName" . }}
    namespace: {{ .Values.controller.namespace }} 
roleRef:
  kind: ClusterRole
  name: {{ include "crusoe-lb-controller.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
